name: Build and Publish (development-v6)
on:
  schedule:
    - cron: "0 5 * * *"
  push:
    branches:
      - development-v6

env:
  dockerhub: ${{ secrets.DOCKERHUB_NAMESPACE }}/pihole
  ghcr: ghcr.io/${{ github.repository_owner }}/pihole

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        registry: [dockerhub, ghcr]
        platform: [linux/amd64, linux/386, linux/arm/v6, linux/arm/v7, linux/arm64]
        container: [3.18]
        include:
          - registry: dockerhub
            platform: linux/riscv64
            container: edge
          - registry: ghcr
            platform: linux/riscv64
            container: edge
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Docker meta (Docker Hub and GitHub Container Registry)
        id: meta
        uses: docker/metadata-action@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          images: |
            ${{ env[matrix.registry] }}
          flavor: |
            latest=false
          tags: |
            development-v6

      - name: Login to DockerHub and GitHub Container Registry
        uses: ./.github/actions/login-repo
        with:
          docker_username: ${{ secrets.DOCKERHUB_USER }}
          docker_password: ${{ secrets.DOCKERHUB_PASS }}
          ghcr_username: ${{ github.repository_owner }}
          ghcr_password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ matrix.platform}}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build container and push by digest (${{ matrix.registry }})
        id: build
        uses: docker/build-push-action@v5
        with:
          context: ./src/
          platforms: ${{ matrix.platform }}
          build-args: |
            PIHOLE_DOCKER_TAG=${{ steps.meta.outputs.version }}
            CONTAINER=${{ matrix.container }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: |
            type=image,name=${{ env[matrix.registry] }},push-by-digest=true,name-canonical=true,push=true

      - name: Export digests
        run: |
          mkdir -p /tmp/digests/${{ matrix.registry }}
          digest_docker="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${{ matrix.registry }}/${digest_docker#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1

  # Merge all the digests into a single file
  # If we would push immediately above, the individual runners would overwrite each other's images
  # https://docs.docker.com/build/ci/github-actions/multi-platform/#distribute-build-across-multiple-runners
  merge-and-deploy:
    strategy:
      fail-fast: false
      matrix:
        registry: [dockerhub, ghcr]
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Download digests
        uses: actions/download-artifact@v3
        with:
          name: digests
          path: /tmp/digests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub and GitHub Container Registry
        uses: ./.github/actions/login-repo
        with:
          docker_username: ${{ secrets.DOCKERHUB_USER }}
          docker_password: ${{ secrets.DOCKERHUB_PASS }}
          ghcr_username: ${{ github.repository_owner }}
          ghcr_password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta (Docker Hub and GitHub Container Registry)
        id: meta
        uses: docker/metadata-action@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          images: |
            ${{ env[matrix.registry] }}
          flavor: |
            latest=false
          tags: |
            development-v6

      - name: Create manifest list and push (${{ matrix.registry }})
        working-directory: /tmp/digests/${{ matrix.registry }}
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ env[matrix.registry] }}@sha256:%s ' *)

      - name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ env[matrix.registry] }}:${{ steps.meta.outputs.version }}
